name: "gurps"
services:
  usersservice:
    image: ${DOCKER_REGISTRY-}gurps/users-service
    container_name: "UsersService"
    build:
      context: .
      dockerfile: src/UsersService/UsersService.Presentation/Dockerfile
    depends_on:
      - usersservicepg
      - usersserviceredis
    volumes:
      - usersservice_local_data:/app/wwwroot
    ports:
      - 8080:8080
      - 8090:8090

  usersservicepg:
    image: postgres:latest
    container_name: "UsersServicePostgres"
    environment:
      POSTGRES_USER: users_user
      POSTGRES_PASSWORD: users_password
      POSTGRES_DB: usersdb
    volumes:
      - users_pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  usersserviceredis:
    image: redis:latest
    container_name: "UsersServiceRedis"
    environment:
      REDIS_PASSWORD: users_redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - users_redis_data:/data
    ports:
      - 6379:6379

  usersservicemongo:
    image: mongo:latest
    container_name: "UsersServiceMongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
      MONGO_INITDB_DATABASE: mongousersdb
    volumes:
      - users_mongo_data:/data/db
    ports:
      - 27017:27017

  gameservice:
    image: ${DOCKER_REGISTRY-}gurps/game-service
    container_name: "GameService"
    build:
      context: .
      dockerfile: src/GameService/GameService.Presentation/Dockerfile
    ports:
      - 8081:8080

  communicationservice:
    image: ${DOCKER_REGISTRY-}gurps/communication-service
    container_name: "CommunicationService"
    build:
      context: .
      dockerfile: src/CommunicationService/CommunicationService.Presentation/Dockerfile
    volumes:
      - communication_local_data:/app/wwwroot
    ports:
      - 8082:8080

  communicationservicemongo:
    image: mongo:latest
    container_name: "CommunicationServiceMongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_communication
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
      MONGO_INITDB_DATABASE: mongocommunicationdb
    volumes:
      - communication_mongo_data:/data/db
    ports:
      - 27019:27017

volumes:
  users_pg_data:
  users_redis_data:
  users_mongo_data:
  usersservice_local_data:
  communication_local_data:
  communication_mongo_data:  